"""PR-C tests: F2 algebra wiring via ``state.implicit_path_conditions``.

These tests cover the per-token implicit grok constraint pipeline:

* synthesizer / parser round-trip — bodies generated by the grok extractor
  must be parseable by ``extract_regex_literal``.
* state plumbing — clone, merge-intersection, dedupe, rename, invalidation.
* end-to-end analyzer behavior — branch reachability decisions reflect the
  algebra-amplified constraint, including cross-feature interaction with
  PR-A's ``!~`` extraction.
* mutate propagation — rename rewrites the field reference in the
  constraint; gsub / replace / convert / case / split / join / remove drop
  the constraint (sound underapproximation).
* branch-merge intersection — a constraint introduced inside one branch
  must not survive the merge with a parallel branch that lacks it.
* cache discipline — interleaved grok-then-predicate analyses do not blow
  out the algebra LRU cache.
"""

from __future__ import annotations

import re

import pytest

from parser_lineage_analyzer import ReverseParser
from parser_lineage_analyzer._analysis_condition_facts import (
    _conditions_are_compatible_cached,
    condition_is_contradicted,
    conditions_are_compatible,
)
from parser_lineage_analyzer._analysis_state import AnalyzerState
from parser_lineage_analyzer._grok_patterns import bundled_library, expand_pattern
from parser_lineage_analyzer._plugins_extractors import (
    _MAX_IMPLICIT_GROK_BODY_BYTES,
    _is_trivial_grok_body,
    _synthesize_implicit_grok_condition,
)
from parser_lineage_analyzer._regex_algebra import extract_regex_literal
from tests._typing_helpers import expect_mapping, expect_mapping_list, expect_str


def _summary_codes(parser: ReverseParser) -> set[str]:
    return {
        expect_str(expect_mapping(w)["code"])
        for w in expect_mapping_list(parser.analysis_summary()["structured_warnings"])
    }


# ---------------------------------------------------------------------------
# Synthesizer / parser round-trip
# ---------------------------------------------------------------------------


class TestSynthesizerRoundTrip:
    """Synthesized condition strings must parse back via ``extract_regex_literal``.

    The implicit-condition pipeline appends strings that downstream code
    parses through the same machinery as user-written conditions. If the
    escaping is wrong, the algebra silently degrades to UNKNOWN — sound but
    a precision regression invisible to end-to-end tests.
    """

    @pytest.mark.parametrize(
        "body",
        [
            r"^[A-Z]+$",
            r"foo/bar",  # unescaped slash — must be backslash-escaped in synthesis
            r"^[+-]?[0-9]+$",
            r"(?:[A-Fa-f0-9]{4}\.){2}[A-Fa-f0-9]{4}",
            r"(?:[Aa]lert|[Tt]race|[Dd]ebug)",
        ],
    )
    def test_round_trip_parses(self, body: str) -> None:
        # The synthesizer's contract is that the produced string is
        # parseable by ``extract_regex_literal`` and surfaces the body as a
        # positive match — exact byte-equality after un-escape would
        # require inverting the slash + backslash escape, which is not
        # what downstream consumers do.
        synthesized = _synthesize_implicit_grok_condition("token", body)
        assert synthesized is not None
        extracted = extract_regex_literal(synthesized)
        assert extracted is not None, f"failed to parse synthesized condition: {synthesized!r}"
        assert getattr(extracted, "is_match", True) is True
        # The token reference round-trips. The synthesizer always emits
        # the bracketed form (``[token]``); ``extract_regex_literal``
        # preserves the bracket form as it appears in the source, so the
        # round-trip is bracket-exact.
        assert extracted.field == "[token]"

    def test_synthesizer_rejects_oversize_body(self) -> None:
        oversize = "a" * (_MAX_IMPLICIT_GROK_BODY_BYTES + 1)
        assert _synthesize_implicit_grok_condition("t", oversize) is None

    def test_synthesizer_accepts_at_byte_limit(self) -> None:
        at_limit = "a" * _MAX_IMPLICIT_GROK_BODY_BYTES
        assert _synthesize_implicit_grok_condition("t", at_limit) is not None

    @pytest.mark.parametrize("body", ["", ".*", ".+", "(.*)", "(.+)", "(?:.*)", "(?:.+)"])
    def test_trivial_bodies_skipped(self, body: str) -> None:
        # The synthesizer itself doesn't check — that gate lives in the
        # extractor — but the trivial-body classifier must agree on what
        # counts as uninformative.
        assert _is_trivial_grok_body(body)

    @pytest.mark.parametrize(
        "body,sample,should_match",
        [
            # Backslash escapes must keep their regex meaning. The earlier
            # implementation doubled all backslashes, turning ``\d`` into
            # ``\\d`` (literal backslash+d) and silently corrupting every
            # bundled pattern that uses a character-class escape.
            (r"\d+", "12345", True),
            (r"\d+", "abcde", False),
            (r"\b\w+\b", "hello world", True),
            (r"\bfoo\b", "barbaz", False),
            (r"^\s*[A-Z]+\s*$", "  HELLO  ", True),
            (r"^\s*[A-Z]+\s*$", "hello", False),
        ],
    )
    def test_synthesizer_preserves_regex_escape_semantics(self, body: str, sample: str, should_match: bool) -> None:
        # Regression for the backslash-escape soundness bug: synthesize a
        # constraint, parse it back, and verify the parsed regex matches
        # the same strings as the original body. If the synthesizer
        # doubles backslashes the parsed pattern matches a totally
        # different language and downstream contradiction reasoning
        # silently goes wrong.
        synthesized = _synthesize_implicit_grok_condition("token", body)
        assert synthesized is not None
        extracted = extract_regex_literal(synthesized)
        assert extracted is not None
        # The body parser preserves the source bytes (modulo slash
        # delimiter handling). Compiling the extracted body must accept
        # / reject the same samples as the original body.
        original = re.compile(body)
        extracted_pattern = re.compile(extracted.body)
        assert bool(original.search(sample)) == should_match
        assert bool(extracted_pattern.search(sample)) == should_match, (
            f"backslash escape corrupted regex semantics: body={body!r} extracted={extracted.body!r} sample={sample!r}"
        )

    @pytest.mark.parametrize("token", ["weird]name", "with[bracket", "has/slash", "back\\slash", "line\nbreak"])
    def test_synthesizer_rejects_invalid_token_chars(self, token: str) -> None:
        # Token names containing ``[``, ``]``, ``/``, ``\``, newline, or
        # carriage return would produce a malformed condition string.
        # The synthesizer must skip them rather than emit a string the
        # algebra silently rejects.
        assert _synthesize_implicit_grok_condition(token, r"\d+") is None

    def test_synthesizer_rejects_body_with_newline(self) -> None:
        assert _synthesize_implicit_grok_condition("t", "abc\ndef") is None
        assert _synthesize_implicit_grok_condition("t", "abc\rdef") is None

    def test_synthesizer_max_body_bytes_tracks_algebra_constant(self) -> None:
        # The synthesizer's body cap must stay coupled to the algebra's
        # constant — drift would mean either skipping constraints
        # unnecessarily or attempting to synthesize ones that get
        # rejected later.
        from parser_lineage_analyzer._regex_algebra import MAX_REGEX_BODY_BYTES

        assert _MAX_IMPLICIT_GROK_BODY_BYTES == MAX_REGEX_BODY_BYTES


# ---------------------------------------------------------------------------
# State plumbing
# ---------------------------------------------------------------------------


class TestStatePlumbing:
    def test_dedupe_returns_false_on_duplicate(self) -> None:
        state = AnalyzerState()
        cond = "[t] =~ /^[A-Z]+$/"
        assert state.add_implicit_path_condition(cond) is True
        assert state.add_implicit_path_condition(cond) is False
        assert state.implicit_path_conditions == [cond]

    def test_dedupe_rejects_empty_string(self) -> None:
        state = AnalyzerState()
        assert state.add_implicit_path_condition("") is False
        assert state.implicit_path_conditions == []

    def test_clone_propagates_implicit_conditions(self) -> None:
        state = AnalyzerState()
        state.add_implicit_path_condition("[t] =~ /^x$/")
        state.add_implicit_path_condition("[u] =~ /^y$/")
        clone = state.clone()
        assert clone.implicit_path_conditions == state.implicit_path_conditions
        # Independence: mutating clone must not affect original.
        clone.add_implicit_path_condition("[v] =~ /^z$/")
        assert "[v] =~ /^z$/" not in state.implicit_path_conditions
        # Dedupe set carried over so the clone won't re-add.
        assert clone.add_implicit_path_condition("[t] =~ /^x$/") is False

    def test_invalidate_drops_only_matching_token(self) -> None:
        state = AnalyzerState()
        state.add_implicit_path_condition("[port] =~ /^[0-9]+$/")
        state.add_implicit_path_condition("[host] =~ /^[a-z.]+$/")
        state.invalidate_implicit_path_conditions_for_token("port")
        assert state.implicit_path_conditions == ["[host] =~ /^[a-z.]+$/"]
        # Re-adding the dropped condition must succeed (dedupe set was
        # rebuilt to drop the stale entry).
        assert state.add_implicit_path_condition("[port] =~ /^[0-9]+$/") is True

    def test_rename_rewrites_leading_token_only(self) -> None:
        state = AnalyzerState()
        state.add_implicit_path_condition("[src] =~ /^x$/")
        state.add_implicit_path_condition("[unrelated] =~ /^src$/")  # body mentions src — must NOT be rewritten
        state.rename_implicit_path_conditions("src", "dst")
        assert "[dst] =~ /^x$/" in state.implicit_path_conditions
        assert "[unrelated] =~ /^src$/" in state.implicit_path_conditions

    def test_rename_noop_on_self_rename(self) -> None:
        state = AnalyzerState()
        state.add_implicit_path_condition("[t] =~ /^x$/")
        before = list(state.implicit_path_conditions)
        state.rename_implicit_path_conditions("t", "t")
        assert state.implicit_path_conditions == before

    def test_invalidate_drops_descendant_constraints(self) -> None:
        # When a parent token is overwritten, any constraints on its
        # descendants (``[parent.child]``) become stale and must be
        # dropped — the post-overwrite value at ``parent`` no longer
        # has the structured children that the constraints described.
        state = AnalyzerState()
        state.add_implicit_path_condition("[user] =~ /^[A-Z]+$/")
        state.add_implicit_path_condition("[user.id] =~ /^[0-9]+$/")
        state.add_implicit_path_condition("[user.email] =~ /^[a-z]+@/")
        state.add_implicit_path_condition("[unrelated] =~ /^x$/")
        state.invalidate_implicit_path_conditions_for_token("user")
        # ``user`` and all ``user.*`` descendants gone; unrelated stays.
        assert state.implicit_path_conditions == ["[unrelated] =~ /^x$/"]

    def test_invalidate_does_not_drop_sibling_with_shared_prefix(self) -> None:
        # ``user`` invalidation must drop ``[user]`` and ``[user.x]`` but
        # not ``[user_alt]`` — the latter is a separate token whose name
        # only happens to start with the same letters.
        state = AnalyzerState()
        state.add_implicit_path_condition("[user] =~ /^x$/")
        state.add_implicit_path_condition("[user_alt] =~ /^y$/")
        state.invalidate_implicit_path_conditions_for_token("user")
        assert state.implicit_path_conditions == ["[user_alt] =~ /^y$/"]

    def test_rename_dedupes_collisions_with_existing_dst_constraints(self) -> None:
        # If src→dst rename produces a constraint that already exists for
        # dst, the duplicate must be folded so the list stays canonical
        # for cache-key partitioning.
        state = AnalyzerState()
        state.add_implicit_path_condition("[a] =~ /^X$/")
        state.add_implicit_path_condition("[b] =~ /^X$/")
        state.rename_implicit_path_conditions("a", "b")
        # Both constraints would rewrite to ``[b] =~ /^X$/``; dedupe to one.
        assert state.implicit_path_conditions == ["[b] =~ /^X$/"]
        assert state._implicit_path_conditions_seen == {"[b] =~ /^X$/"}


# ---------------------------------------------------------------------------
# API arity / contradiction routing
# ---------------------------------------------------------------------------


class TestContradictionRouting:
    """``implicit_conditions`` argument must reach the algebra and be
    folded with ``prior_conditions`` for cache-key partitioning."""

    def test_implicit_drives_contradiction(self) -> None:
        # Same body, opposite operators → must contradict via implicit-arg.
        body = r"^[a-z]+$"
        implicit = (f"[t] =~ /{body}/",)
        assert condition_is_contradicted(f"[t] !~ /{body}/", (), implicit) is True
        assert conditions_are_compatible([f"[t] !~ /{body}/"], implicit) is False

    def test_implicit_equivalent_to_prior_for_contradiction(self) -> None:
        body = r"^[a-z]+$"
        cond = f"[t] !~ /{body}/"
        prior = (f"[t] =~ /{body}/",)
        via_prior = condition_is_contradicted(cond, prior, ())
        via_implicit = condition_is_contradicted(cond, (), prior)
        assert via_prior == via_implicit is True

    def test_implicit_default_empty_preserves_pre_pr_c_behavior(self) -> None:
        # Without implicit arg, behavior must be identical to PR-A baseline.
        cond = '[t] == "x"'
        prior_only = condition_is_contradicted(cond, ('[t] != "x"',))
        prior_with_explicit_empty_implicit = condition_is_contradicted(cond, ('[t] != "x"',), ())
        assert prior_only is True
        assert prior_with_explicit_empty_implicit is True


# ---------------------------------------------------------------------------
# End-to-end: cross-feature with PR-A (!~ extraction)
# ---------------------------------------------------------------------------


_INT_BODY = expand_pattern("INT", bundled_library())  # cached, deterministic


class TestCrossFeatureWithF1NegMatch:
    """Grok captures a typed value, then a downstream ``!~`` predicate
    against the same body must collapse the branch (PR-C × PR-A)."""

    def test_grok_int_then_neg_match_same_body_collapses_branch(self) -> None:
        # The synthesizer produces ``[port] =~ /(?:[+-]?(?:[0-9]+))/`` from
        # the bundled INT pattern. A ``!~`` predicate against the same body
        # is a textbook UNSAT for the algebra.
        assert _INT_BODY is not None
        code = f"""
        filter {{
          grok {{ match => {{ "message" => "%{{INT:port}}" }} }}
          if [port] !~ /{_INT_BODY}/ {{
            mutate {{ replace => {{ "event.idm.read_only_udm.principal.port" => "UNREACHABLE" }} }}
          }} else {{
            mutate {{ replace => {{ "event.idm.read_only_udm.principal.port" => "REACHABLE" }} }}
          }}
        }}
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        # Only the else branch is reachable — the if branch contradicts the
        # implicit grok constraint.
        expressions = [m.expression for m in result.mappings]
        assert "REACHABLE" in expressions
        assert "UNREACHABLE" not in expressions
        assert "unreachable_branch" in _summary_codes(parser)

    def test_grok_int_then_literal_eq_non_int_collapses_branch(self) -> None:
        # ``[port] == "abc"`` — "abc" doesn't satisfy INT regex, so the
        # branch is unreachable.
        code = """
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          if [port] == "abc" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "UNREACHABLE" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "REACHABLE" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        expressions = [m.expression for m in result.mappings]
        assert "UNREACHABLE" not in expressions
        assert "REACHABLE" in expressions
        assert "unreachable_branch" in _summary_codes(parser)

    def test_repeated_grok_into_same_token_does_not_falsely_collapse(self) -> None:
        # Regression for the re-grok soundness bug: two grok calls into the
        # same captured name register both bodies as implicit constraints.
        # Runtime semantics is *disjunction* (one or the other matched);
        # treating the constraints as conjunction would falsely flag
        # literals from either alternative as contradictory.
        #
        # Repro: %{INT:tok} then %{UUID:tok}. Both bodies fit under the
        # algebra cap. A literal "123" satisfies INT; a literal UUID
        # satisfies UUID. Neither should be flagged unreachable.
        code = """
        filter {
          grok { match => { "a" => "%{INT:tok}" } }
          grok { match => { "b" => "%{UUID:tok}" } }
          if [tok] == "123" {
            mutate { replace => { "event.idm.read_only_udm.principal.user.userid" => "INT_LIT" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.user.userid" => "OTHER" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.user.userid")
        expressions = sorted(m.expression for m in result.mappings)
        # "123" is a valid INT value if grok1 matched; the if-branch must
        # remain reachable.
        assert "INT_LIT" in expressions, (
            f"re-grok soundness regression: expected INT_LIT to remain reachable, got {expressions!r}"
        )
        assert "OTHER" in expressions

    def test_grok_int_then_literal_eq_valid_int_stays_reachable(self) -> None:
        # ``[port] == "443"`` is consistent with the implicit constraint —
        # the branch must stay reachable.
        code = """
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          if [port] == "443" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "HTTPS" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "OTHER" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        expressions = sorted(m.expression for m in result.mappings)
        assert expressions == ["HTTPS", "OTHER"]
        assert "unreachable_branch" not in _summary_codes(parser)

    def test_regrok_with_oversize_body_invalidates_prior_constraint(self) -> None:
        # Regression for v0.1.0 release-hardening fix: a re-grok whose
        # resolved body exceeds ``MAX_REGEX_BODY_BYTES`` (synthesis
        # returns ``None``) must still invalidate the prior implicit
        # constraint. Otherwise a literal that contradicts the *first*
        # grok's shape gets falsely flagged unreachable, even though the
        # *second* grok overwrote the runtime value with something
        # whose shape we can no longer prove.
        #
        # Repro: grok #1 captures ``%{INT:tok}`` (~19 bytes — synthesis
        # succeeds, prior implicit constraint is ``[tok] =~ /(?:[+-]?(?:[0-9]+))/``).
        # Grok #2 captures ``%{IPV6:tok}`` (1071 bytes — exceeds the
        # 512-byte algebra cap, synthesis returns ``None``). The if-branch
        # tests ``[tok] == "::1"`` — a valid IPv6 literal that does NOT
        # match INT. Pre-fix: stale INT constraint persists, "::1"
        # contradicts ``[tok] =~ /(?:[+-]?(?:[0-9]+))/``, branch wrongly
        # marked unreachable. Post-fix: invalidation runs unconditionally,
        # branch stays reachable.
        from parser_lineage_analyzer._grok_patterns import bundled_library, expand_pattern

        ipv6_body = expand_pattern("IPV6", bundled_library())
        assert ipv6_body is not None
        # Sanity: the test only exercises the bug-window if IPV6 is in
        # the 513..8192 byte range. If a future bundle change resizes
        # it under the cap, switch to a different pattern.
        from parser_lineage_analyzer._regex_algebra import MAX_REGEX_BODY_BYTES

        assert len(ipv6_body.encode("utf-8")) > MAX_REGEX_BODY_BYTES, (
            "test fixture invariant: IPV6 must exceed the algebra body cap"
        )

        code = """
        filter {
          grok { match => { "a" => "%{INT:tok}" } }
          grok { match => { "b" => "%{IPV6:tok}" } }
          if [tok] == "::1" {
            mutate { replace => { "event.idm.read_only_udm.principal.user.userid" => "IPV6_LIT" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.user.userid" => "OTHER" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.user.userid")
        expressions = sorted(m.expression for m in result.mappings)
        # The if-branch is reachable: IPV6 grok overwrote ``tok``, the
        # stale INT constraint must have been dropped, and ``[tok] == "::1"``
        # is no longer flagged as a contradiction.
        assert "IPV6_LIT" in expressions, (
            f"oversize re-grok invalidation regression: expected IPV6_LIT to remain reachable, got {expressions!r}"
        )
        assert "OTHER" in expressions

    def test_regrok_with_oversize_body_drops_prior_implicit_for_token(self) -> None:
        # Companion white-box test: assert the implicit-conditions list
        # state directly. The end-to-end test above proves the user-visible
        # behavior; this test pins the contract to ``state.implicit_path_conditions``
        # so a regression in invalidation surfaces here even if the
        # downstream contradiction routing changes shape.
        from parser_lineage_analyzer._grok_patterns import bundled_library, expand_pattern
        from parser_lineage_analyzer._regex_algebra import MAX_REGEX_BODY_BYTES

        ipv6_body = expand_pattern("IPV6", bundled_library())
        assert ipv6_body is not None
        assert len(ipv6_body.encode("utf-8")) > MAX_REGEX_BODY_BYTES

        code = """
        filter {
          grok { match => { "a" => "%{INT:tok}" } }
          grok { match => { "b" => "%{IPV6:tok}" } }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        # No implicit constraint should remain on ``tok``: the second
        # grok's body is oversize so synthesis was skipped, but
        # invalidation still ran and dropped the INT shape constraint.
        assert not any("[tok]" in cond for cond in parser.state.implicit_path_conditions), (
            f"oversize re-grok left a stale [tok] constraint: {parser.state.implicit_path_conditions!r}"
        )


# ---------------------------------------------------------------------------
# Mutate propagation: rename / gsub / remove
# ---------------------------------------------------------------------------


class TestMutatePropagation:
    def test_rename_preserves_implicit_constraint(self) -> None:
        # Capture into ``port``, rename to ``client_port``, then check
        # against the new name. Constraint must follow the rename.
        code = """
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          mutate { rename => { "port" => "client_port" } }
          if [client_port] == "abc" {
            mutate { replace => { "event.idm.read_only_udm.network.client.port" => "UNREACHABLE" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.network.client.port" => "REACHABLE" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("network.client.port")
        expressions = [m.expression for m in result.mappings]
        assert "UNREACHABLE" not in expressions
        assert "REACHABLE" in expressions
        assert "unreachable_branch" in _summary_codes(parser)

    def test_gsub_drops_implicit_constraint(self) -> None:
        # Capture into ``port``, gsub it (mutates value), then check the
        # impossible literal. The constraint must be dropped — branch stays
        # reachable (sound underapproximation).
        code = r"""
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          mutate { gsub => ["port", "[0-9]", "X"] }
          if [port] == "abc" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "REACHABLE_AFTER_GSUB" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "ELSE" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        expressions = sorted(m.expression for m in result.mappings)
        # Both branches must be reachable post-gsub — gsub could rewrite the
        # value to "abc"-compatible content (e.g. "abc" matches if every
        # digit is replaced with an X-prefixed letter run).
        assert "REACHABLE_AFTER_GSUB" in expressions
        assert "ELSE" in expressions

    def test_replace_drops_implicit_constraint(self) -> None:
        code = """
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          mutate { replace => { "port" => "literal_string" } }
          if [port] == "abc" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "REACHABLE_AFTER_REPLACE" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "ELSE" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        expressions = sorted(m.expression for m in result.mappings)
        # ``replace`` overwrites with a literal; any prior INT constraint is
        # moot. Both branches stay reachable.
        assert "REACHABLE_AFTER_REPLACE" in expressions
        assert "ELSE" in expressions

    def test_add_field_drops_implicit_constraint_so_appended_literal_stays_reachable(
        self,
    ) -> None:
        # Regression for the add_field soundness bug. ``add_field`` widens
        # an existing field into an array (Logstash semantics) — the
        # appended literal need not satisfy the captured pattern, so the
        # implicit string-regex constraint must be dropped to keep
        # downstream predicates against the appended value reachable.
        code = """
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          mutate { add_field => { "port" => "appended_literal" } }
          if [port] == "appended_literal" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "MATCHED_APPENDED" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "OTHER" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        expressions = sorted(m.expression for m in result.mappings)
        assert "MATCHED_APPENDED" in expressions, (
            f"add_field soundness regression: expected MATCHED_APPENDED to remain reachable, got {expressions!r}"
        )
        assert "OTHER" in expressions

    def test_convert_drops_implicit_constraint(self) -> None:
        code = """
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          mutate { convert => { "port" => "integer" } }
          if [port] == "abc" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "REACHABLE_AFTER_CONVERT" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "ELSE" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        expressions = sorted(m.expression for m in result.mappings)
        assert "REACHABLE_AFTER_CONVERT" in expressions
        assert "ELSE" in expressions

    def test_rename_onto_existing_grok_dest_drops_old_dest_constraint(self) -> None:
        # Regression for the rename-onto-existing-dest soundness bug:
        # if both src and dest had implicit constraints (two grok captures),
        # rename overwrites dest's value. The pre-existing dest constraint
        # must be dropped before src's is rewritten — otherwise the algebra
        # sees both shapes simultaneously and may flag valid literals
        # unreachable.
        code = """
        filter {
          grok { match => { "a" => "%{UUID:dst}" } }
          grok { match => { "b" => "%{INT:src}" } }
          mutate { rename => { "src" => "dst" } }
          if [dst] == "123" {
            mutate { replace => { "event.idm.read_only_udm.principal.user.userid" => "INT_VAL" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.user.userid" => "OTHER" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.user.userid")
        expressions = sorted(m.expression for m in result.mappings)
        # After rename, dst's value is the renamed src's value (INT-shape).
        # "123" is INT-compatible; the if-branch must remain reachable.
        # If the old UUID constraint on dst survived, "123" would be
        # flagged unreachable (UUID requires hyphens).
        assert "INT_VAL" in expressions, (
            f"rename-onto-existing-dest regression: expected INT_VAL reachable, got {expressions!r}"
        )

    def test_remove_field_drops_implicit_constraint(self) -> None:
        # After ``remove_field``, the implicit constraint must NOT make
        # downstream predicates spuriously contradictory.
        code = """
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          mutate { remove_field => ["port"] }
          if [port] == "abc" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "AFTER_REMOVE_IF" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "AFTER_REMOVE_ELSE" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        # No regression: analyzer doesn't crash, and the unreachable_branch
        # warning isn't emitted for the if-branch (the constraint was
        # invalidated, so the predicate falls back to UNKNOWN-as-compatible).
        # Either branch may appear in the results depending on remove
        # semantics for new tokens; what matters is no spurious
        # contradiction.
        codes = _summary_codes(parser)
        # The if-branch must not be flagged as unreachable due to the
        # (now-invalidated) INT constraint.
        if "unreachable_branch" in codes:
            structured = parser.analysis_summary()["structured_warnings"]
            for w in expect_mapping_list(structured):
                if expect_str(expect_mapping(w)["code"]) == "unreachable_branch":
                    msg = expect_str(expect_mapping(w)["message"])
                    assert '[port] == "abc"' not in msg, (
                        f"if-branch was wrongly flagged unreachable after remove_field: {msg!r}"
                    )


# ---------------------------------------------------------------------------
# Branch-merge intersection
# ---------------------------------------------------------------------------


class TestBranchMergeIntersection:
    def test_grok_inside_if_branch_does_not_survive_merge(self) -> None:
        # Grok runs only in the if-branch. After the if/else completes,
        # the implicit constraint must NOT apply post-merge — the value
        # might come from the else-branch where grok never ran.
        code = """
        filter {
          if [type] == "log" {
            grok { match => { "message" => "%{INT:port}" } }
          } else {
            mutate { add_field => { "port" => "fallback" } }
          }
          if [port] == "abc" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "POST_MERGE" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        # The post-merge if-branch must NOT be flagged unreachable: the
        # constraint only applied in one survivor, intersection drops it.
        codes = _summary_codes(parser)
        if "unreachable_branch" in codes:
            structured = parser.analysis_summary()["structured_warnings"]
            for w in expect_mapping_list(structured):
                if expect_str(expect_mapping(w)["code"]) == "unreachable_branch":
                    msg = expect_str(expect_mapping(w)["message"])
                    assert '[port] == "abc"' not in msg, (
                        "post-merge predicate was wrongly flagged unreachable; "
                        "the implicit constraint should not survive intersection."
                    )

    def test_grok_in_both_branches_survives_merge(self) -> None:
        # Same grok in both branches → constraint applies to all survivors,
        # so post-merge predicate against impossible literal must collapse.
        code = """
        filter {
          if [type] == "log" {
            grok { match => { "message" => "%{INT:port}" } }
          } else {
            grok { match => { "raw" => "%{INT:port}" } }
          }
          if [port] == "abc" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "POST_MERGE_UNREACHABLE" } }
          } else {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "POST_MERGE_REACHABLE" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        expressions = sorted(m.expression for m in result.mappings)
        # Implicit constraint applies in both surviving branches → algebra
        # collapses the impossible-literal check post-merge.
        assert "POST_MERGE_UNREACHABLE" not in expressions
        assert "POST_MERGE_REACHABLE" in expressions
        # Strengthening assertion: the unreachable_branch warning must be
        # emitted and reference the post-merge predicate. Without this,
        # a future change that drops constraints across merge would let
        # the test pass for the wrong reason (POST_MERGE_UNREACHABLE
        # could be missing because of an unrelated bug).
        codes = _summary_codes(parser)
        assert "unreachable_branch" in codes, (
            "expected unreachable_branch warning when implicit constraint "
            f"survives intersection-of-survivors merge; got codes={sorted(codes)!r}"
        )


# ---------------------------------------------------------------------------
# Output-stripping audit (programmatic guard)
# ---------------------------------------------------------------------------


class TestOutputStripping:
    def test_implicit_conditions_never_appear_in_lineage_conditions(self) -> None:
        code = """
        filter {
          grok { match => { "message" => "%{INT:port}" } }
          if [port] == "443" {
            mutate { replace => { "event.idm.read_only_udm.principal.port" => "https" } }
          }
        }
        """
        parser = ReverseParser(code)
        parser.analyze()
        result = parser.query("principal.port")
        for mapping in result.mappings:
            for cond in mapping.conditions:
                # Implicit-condition synthesis emits ``[<token>] =~ /<body>/``;
                # any such string showing up in user-visible lineage means a
                # leak. (The user-typed equality predicate uses ``==``, not
                # ``=~``, so this is a tight guard.)
                assert not re.match(r"^\[[^\]]+\]\s*=~", cond), (
                    f"implicit condition leaked into user-visible lineage: {cond!r}"
                )


# ---------------------------------------------------------------------------
# Cache discipline
# ---------------------------------------------------------------------------


class TestCacheDiscipline:
    def test_repeated_grok_then_predicate_does_not_blow_cache(self) -> None:
        # Many distinct (grok, predicate) interleavings. Cache must stay
        # bounded — the LRU's maxsize is the safety net, but we want to
        # make sure adding implicit conditions doesn't multiply the
        # cardinality unexpectedly.
        for i in range(50):
            code = f"""
            filter {{
              grok {{ match => {{ "message" => "%{{INT:port_{i}}}" }} }}
              if [port_{i}] == "{i}" {{
                mutate {{ replace => {{ "event.idm.read_only_udm.principal.port" => "p{i}" }} }}
              }}
            }}
            """
            parser = ReverseParser(code)
            parser.analyze()
        cache_info_after = _conditions_are_compatible_cached.cache_info()
        # currsize must not exceed maxsize. (A bug that mis-keys would
        # push currsize toward maxsize quickly.)
        assert cache_info_after.currsize <= cache_info_after.maxsize


# ---------------------------------------------------------------------------
# Rename-invariance property
# ---------------------------------------------------------------------------


class TestRenameInvarianceProperty:
    """Reachability of a predicate must not depend on whether the token
    was renamed mid-pipeline — provided the predicate references the
    post-rename name in the rename case and the original name in the no-
    rename case.
    """

    @pytest.mark.parametrize(
        "predicate_literal,expected_unreachable",
        [
            ('"abc"', True),  # incompatible with INT → both fixtures must agree it's unreachable
            ('"443"', False),  # compatible with INT → both fixtures must agree it's reachable
        ],
    )
    def test_rename_preserves_reachability_decision(self, predicate_literal: str, expected_unreachable: bool) -> None:
        without_rename = f"""
        filter {{
          grok {{ match => {{ "message" => "%{{INT:port}}" }} }}
          if [port] == {predicate_literal} {{
            mutate {{ replace => {{ "event.idm.read_only_udm.principal.port" => "MATCHED" }} }}
          }}
        }}
        """
        with_rename = f"""
        filter {{
          grok {{ match => {{ "message" => "%{{INT:port}}" }} }}
          mutate {{ rename => {{ "port" => "client_port" }} }}
          if [client_port] == {predicate_literal} {{
            mutate {{ replace => {{ "event.idm.read_only_udm.principal.port" => "MATCHED" }} }}
          }}
        }}
        """
        p1 = ReverseParser(without_rename)
        p1.analyze()
        p2 = ReverseParser(with_rename)
        p2.analyze()
        c1 = _summary_codes(p1)
        c2 = _summary_codes(p2)
        assert ("unreachable_branch" in c1) == expected_unreachable
        assert ("unreachable_branch" in c2) == expected_unreachable, (
            f"rename changed reachability decision: without_rename={c1!r}, with_rename={c2!r}"
        )
